version: "1"
adapters:
  my_topo_soil_write_func:
    comment: My topoflow soil write adapter
    adapter: funcs.Topoflow4SoilWriteFunc
    inputs:
      layer: ""
      input_dir: "/ws/oct_eval_data/soilGrids/"
      output_dir: "/ws/examples/scotts_transformations/tmp/soil_lol_kuru_l"
      DEM_bounds: "23.995416666666, 6.532916666667, 28.020416666666, 9.566250000000"
      DEM_ncols: "483"
      DEM_nrows: "364"
      DEM_xres_arcsecs: "30"
      DEM_yres_arcsecs: "30"