version: "1"
adapters:
  my_topo_climate_write_func:
    comment: My topoflow climate write adapter
    adapter: funcs.Topoflow4ClimateWriteFunc
    inputs:
      input_dir: "/data/mint/gpm"
      temp_dir: "/data/mint/gpm_grid_lol_kuru"
      output_file: "/data/mint/lol_kuru/climate_all.rt"
      DEM_bounds: "23.995416666666, 6.532916666667, 28.020416666666, 9.566250000000"
      DEM_ncols: "483"
      DEM_nrows: "364"
      DEM_xres_arcsecs: "30"
      DEM_yres_arcsecs: "30"