version: "1"
description: Data transformation to generate Cycles-ready input files (RTS) from GLDAS weather data sources
inputs:
  soil_dataset_id:
    comment: "SoilGrids Dataset ID"
    value: "fa64cc63-0c9f-409e-a801-9ad73d161c22"  
  gldas_elevation_file_path:
    comment: "Path to the GLDAS elevation file"
    value: "data/download/gldas/GLDASp4_elevation_025d.nc4"
  bounding_box:
    comment: "Bounding box of the extracting region (Horn of Africa here)"
    value: "21.533203125, -5.353521355337321, 51.943359375, 22.67484735118852"  
  num_output_files:
    comment: "Number of output files to create"
    value: 40
  output_path:
    comment: "Path to the output directory"
    value: "examples/gldas2cycles/output_gldas_coordinates/"
  output_prefix:
    comment: "Prefix to be added to the output file names"
    value: "cycles"
adapters:
  gldas2cycles_func:
    comment: Select GLDAS coordinates adapter
    adapter: funcs.SelectGldasCoordinates
    inputs:
      soil_dataset_id: $$.soil_dataset_id
      gldas_elevation_file_path: $$.gldas_elevation_file_path
      bounding_box: $$.bounding_box
      num_output_files: $$.num_output_files
      output_path: $$.output_path
      output_prefix: $$.output_prefix
