version: "1"
description: Data transformation to generate Cycles-ready input files (RTS) from GLDAS weather data sources
inputs:
  gldas_dataset_id:
    comment: "GLDAS Dataset ID"
    value: "5babae3f-c468-4e01-862e-8b201468e3b5"
  gldas_soil_map_file:
    comment: "Path to the GLDAS elevation file"
    value: "examples/gldas2cycles/output_gldas_coordinates/cycles_soilmap.json"  
  start_date:
    comment: "Start date to filter resources in the dataset"
    value: "2000-01-01"
  end_date:
    comment: "End date to filter resources in the dataset"
    value: "2021-03-31"
  batch_numdays:
    comment: "Number of days of GLDAS to load in one go. Keep this number higher for machines with more RAM"
    value: 15
  output_path:
    comment: "Path to the output directory"
    value: "examples/gldas2cycles/output-batched/"
adapters:
  gldas2cycles_func:
    comment: GldasToCycles adapter
    adapter: funcs.GldasToCyclesBatched
    inputs:
      gldas_dataset_id: $$.gldas_dataset_id
      gldas_soil_map_file: $$.gldas_soil_map_file      
      start_date: $$.start_date
      end_date: $$.end_date
      batch_numdays: $$.batch_numdays
      output_path: $$.output_path
