version: "1"
description: Data transformation to generate Cycles-ready input files (RTS) from GLDAS weather data sources
inputs:
  gldas_dataset_id:
    comment: "GLDAS Dataset ID"
    value: "5babae3f-c468-4e01-862e-8b201468e3b5"
  soil_dataset_id:
    comment: "FIXME: Soil Dataset ID - Change to real id"
    value: "ac34f01b-1484-4403-98ea-3a380838cab1"
  start_date:
    comment: "Start date to filter resources in the dataset"
    value: "2000-01-02"
  end_date:
    comment: "End date to filter resources in the dataset"
    value: "2000-01-03"
  gldas_path:
    comment: "Path to GLDAS dataset directory"
    value: "examples/gldas2cycles/GLDAS/"
  output_path:
    comment: "Path to the output directory"
    value: "examples/gldas2cycles/output/"
  output_prefix:
    comment: "Prefix to be added to the output file names"
    value: "cycles"
adapters:
  gldas2cycles_func:
    comment: GLDAS2Cycles adapter
    adapter: funcs.Gldas2CyclesFuncNew
    inputs:
      gldas_dataset_id: $$.gldas_dataset_id
      soil_dataset_id: $$.soil_dataset_id
      start_date: $$.start_date
      end_date: $$.end_date
      gldas_path: $$.gldas_path
      output_path: $$.output_path
      output_prefix: $$.output_prefix
