version: "1"
adapters:
  my_read_func:
    comment: My read func adapter
    adapter: funcs.DcatReadFunc
    inputs:
      dataset_id: N/A
  my_unit_trans_func:
    comment: My unit transform func adapter
    adapter: funcs.UnitTransFunc
    inputs:
      graph: $.my_read_func.data
      unit_value: dcat:measure_1_value
      unit_label: sdmx-attribute:unitMeasure
      unit_desired: $/kg
  my_graph_write_func:
    comment: My graph write func adapter
    adapter: funcs.GraphWriteFunc
    inputs:
      graph: $.my_unit_trans_func.graph
      main_class: qb:Observation
      mapped_columns: {}
      output_file: ./price-test.csv