version: "1"
adapters:
  my_dcat_read_func:
    comment: My read func adapter
    adapter: funcs.DcatReadNoReprFunc
    inputs:
      dataset_id: adfca6fb-ad82-4be3-87d8-8f60f9193e43
  my_topo_climate_write_func:
    comment: My topoflow climate write adapter
    adapter: funcs.Topoflow4ClimateWriteFunc
    inputs:
      input_dir: "$.my_dcat_read_func.data"
      temp_dir: "/data/mint/sample_grid_baro"
      output_file: "/data/mint/sample_baro/climate_all.rt"
      var_name: "HQprecipitation"
      DEM_bounds: "34.221249999999, 7.362083333332, 36.446249999999, 9.503749999999"
      DEM_xres_arcsecs: "30"
      DEM_yres_arcsecs: "30"
  dcat_write_func:
    inputs:
      metadata: '[{"name":"Topoflow weather file - 2011","start_time":"2011-08-18T00:00:00","end_time":"2011-08-18T23:59:59","description":"Weather data transformed from global GPM with bounding box [34.221249999999, 7.362083333332, 36.446249999999, 9.503749999999]","bounding_box":[34.221249999999, 7.362083333332, 36.446249999999, 9.503749999999],"standard_variables":[{"ontology":"ScientificVariablesOntology","name":"atmosphere_water__precipitation_leq_volume_flux","uri":"http://www.geoscienceontology.org/svo/svl/variable#atmosphere%40role%7Esource_water%40role%7Emain_precipitation__precipitation_leq_volume_flux"}]}]'
      resource_path: "$.my_topo_climate_write_func.output_file"
    adapter: funcs.DcatWriteFunc
    comment: My dcat write func adapter
